#PARA UTILIZAR ESSES ENDPOINTS É NECESSÁRIO INSTALAR A EXTENSÃO DO VSCODE "REST CLIENT"
###

GET http://localhost:3333/doutores

###

POST http://localhost:3333/doutores
Content-Type: application/json

{
    "nome": "Doutor Carlos",
    "idade": "54",
    "areaFormacao": "Engenharia"
}

###

PUT http://localhost:3333/doutores/id
Content-Type: application/json

{
    "nome": "Doutor Luiz",
    "idade": "34",
    "areaFormacao": "Advocacia"
}

###

DELETE http://localhost:3333/doutores/id
